// App info
const APP_NAME = "Music Player";

// Default Lists names
const SONGS_UPLOADED_BY_ALL_USERS_LIST_NAME = "Songs uploaded by all users";
const SEARCH_RESULTS_LIST_NAME = "Search results";

const SONGS_UPLOADED_BY_CURRENT_USER_LIST_NAME = "uploaded songs";

// Default Lists ids:
const SONGS_UPLOADED_BY_ALL_USERS_LIST_ID = -2;
const SONGS_UPLOADED_BY_CURRENT_USER_LIST_ID = -1;

// Playlists dropdown
const USER_PLAYLISTS_DROPDOWN_NAME = "Your Playlists";

// Mobile / LapTop Screen Sizes
const MOBILE_MAX_WIDTH = "768px";
const LAPTOP_WIDTH_ONE = "1024px";

// Page container icons
const SMALL_ICON_WIDTH = "18px";
const BIG_ICON_WIDTH = "25px";

// Nav icons
const NAV_SMALL_ICON_HEIGHT = "1.3rem";

// TIMEOUTS
const MESSAGES_TIMEOUT = 3000;
const REDIRECT_TIMEOUT = 3000;

// PAGE NAMES
const HOME_PAGE_NAME = "Home";
const LOGIN_PAGE_NAME = "Login";
const REGISTER_PAGE_NAME = "Register";
const USER_PAGE_NAME = "User";
const ERROR_PAGE_NAME = "404";

// Page paths
const HOME_PAGE_PATH = `/`;
const LOGIN_PAGE_PATH = `/${LOGIN_PAGE_NAME.toLowerCase()}`;
const REGISTER_PAGE_PATH = `/${REGISTER_PAGE_NAME.toLowerCase()}`;
const USER_PAGE_PATH = `/${USER_PAGE_NAME.toLowerCase()}`;

// DASHBOARD FONT
const DASHBOARD_MOBILE_FONT_SIZE = ".7rem";
const DASHBOARD_LAPTOP_FONT_SIZE = "1rem";

// FONT
const LIST_NAME_MOBILE_FONT_SIZE = "0.8rem";
const LIST_NAME_LAPTOP_FONT_SIZE = "1rem";

const FONT_WEIGHT = "600";
const BUTTON_FONT_SIZE = "0.7rem";
const SECTION_TITLE_FONT_SIZE = "0.7rem";

//*** COLORS

const MAIN_COLOR = "#0085FF";
const SECOND_COLOR = "#a5d7f9";
const THIRD_COLOR = "#005db4";
const FOURTH_COLOR = "#5aa7fff2";

// FONT COLORS
const MAIN_FONT_COLOR = "rgb(74, 74, 74)";

const SUCCESS_FONT_COLOR = "rgb(3, 185, 3)";
const ERROR_FONT_COLOR = "rgb(255, 158, 2)";

// BACKGROUND COLORS
const INPUT_BACKGROUND_COLOR = "#e8e8e8";

// Messages
const MESSAGE_DURATION = 4000;

// BUTTONS
const BUTTON_MAX_WIDTH = "150PX";
const INPUT_MAX_WIDTH = "700PX";

export {
  MAIN_COLOR,
  MAIN_FONT_COLOR,
  FONT_WEIGHT,
  BUTTON_FONT_SIZE,
  SUCCESS_FONT_COLOR,
  ERROR_FONT_COLOR,
  SECTION_TITLE_FONT_SIZE,
  APP_NAME,
  HOME_PAGE_NAME,
  LOGIN_PAGE_NAME,
  REGISTER_PAGE_NAME,
  MESSAGE_DURATION,
  DASHBOARD_MOBILE_FONT_SIZE,
  DASHBOARD_LAPTOP_FONT_SIZE,
  INPUT_BACKGROUND_COLOR,
  BUTTON_MAX_WIDTH,
  INPUT_MAX_WIDTH,
  MESSAGES_TIMEOUT,
  REDIRECT_TIMEOUT,
  MOBILE_MAX_WIDTH,
  LAPTOP_WIDTH_ONE,
  SMALL_ICON_WIDTH,
  BIG_ICON_WIDTH,
  SONGS_UPLOADED_BY_ALL_USERS_LIST_NAME,
  SONGS_UPLOADED_BY_CURRENT_USER_LIST_NAME,
  USER_PLAYLISTS_DROPDOWN_NAME,
  SONGS_UPLOADED_BY_CURRENT_USER_LIST_ID,
  SONGS_UPLOADED_BY_ALL_USERS_LIST_ID,
  HOME_PAGE_PATH,
  LOGIN_PAGE_PATH,
  REGISTER_PAGE_PATH,
  USER_PAGE_PATH,
  USER_PAGE_NAME,
  SECOND_COLOR,
  THIRD_COLOR,
  FOURTH_COLOR,
  LIST_NAME_MOBILE_FONT_SIZE,
  LIST_NAME_LAPTOP_FONT_SIZE,
  ERROR_PAGE_NAME,
  NAV_SMALL_ICON_HEIGHT,
  SEARCH_RESULTS_LIST_NAME
};
