// Mobile / LapTop Screen Sizes
const MOBILE_MAX_WIDTH = "768px";

// TIMEOUTS
const MESSAGES_TIMEOUT = 3000;
const REDIRECT_TIMEOUT = 3000;

// GENERAL
const APP_NAME = "Music Player";

// PAGE NAMES
const HOME_PAGE_NAME = "Home";
const LOGIN_PAGE_NAME = "Login";
const REGISTER_PAGE_NAME = "Register";
const MY_ACCOUNT_PAGE_NAME = "Your Account";

// DASHBOARD LINK NAMES
const HOME_LINK_NAME = "Home";
const MY_ACCOUNT_LINK_NAME = "My Account";
const LOGIN_LINK_NAME = "Login";
const REGISTER_LINK_NAME = "Register";
const LOGOUT_LINK_NAME = "Logout";

// DASHBOARD FONT
const DASHBOARD_MOBILE_FONT_SIZE = ".7rem";
const DASHBOARD_LAPTOP_FONT_SIZE = "1rem";

// FONT

const FONT_WEIGHT = "600";
const BUTTON_FONT_SIZE = "0.7rem";
const SECTION_TITLE_FONT_SIZE = "0.7rem";
const LAPTOP_MOVIE_CARD_FONT_SIZE = ".75REM";

const SMALL_FONT_SIZE = ".6rem";

const DASHBOARD_BACKGROUND_COLOR = "#313131b4";

//*** COLORS

const MAIN_COLOR = "#0085FF";

// FONT COLORS
const MAIN_FONT_COLOR = "rgb(74, 74, 74)";
// const MAIN_FONT_COLOR = 'RED';

const SUCCESS_FONT_COLOR = "rgb(3, 185, 3)";
const ERROR_FONT_COLOR = "rgb(255, 158, 2)";

// BACKGROUND COLORS
const BACKGROUND_COLOR_ONE = "#4a4a4aa8";
const PAGE_BACKGROUND_COLOR = "#2e2e2e";
const INPUT_BACKGROUND_COLOR = "rgb(0, 0, 0)";

// SYMBOLS COLORS
const FAVORITE_SYMBOL_COLOR = "#ffffffda";
const FAVORITE_SYMBOL_BACKGROUND_COLOR = "#4f4f4f6f";

// SYMBOLS
const FAVORITE_MOVIE_SYMBOL = "";

// Messages
const MESSAGE_DURATION = 4000;

// MOVIES GRID
const MOBILE_MOVIES_GRID_GAP = "0.5REM";
const LAPTOP_MOVIES_GRID_GAP = "1REM";

// BUTTONS
const BUTTON_MAX_WIDTH = "800PX";
const INPUT_MAX_WIDTH = "800PX";

export {
  MAIN_COLOR,
  MAIN_FONT_COLOR,
  FONT_WEIGHT,
  BUTTON_FONT_SIZE,
  SMALL_FONT_SIZE,
  PAGE_BACKGROUND_COLOR,
  DASHBOARD_BACKGROUND_COLOR,
  HOME_LINK_NAME,
  MY_ACCOUNT_LINK_NAME,
  LOGIN_LINK_NAME,
  REGISTER_LINK_NAME,
  LOGOUT_LINK_NAME,
  SUCCESS_FONT_COLOR,
  ERROR_FONT_COLOR,
  SECTION_TITLE_FONT_SIZE,
  BACKGROUND_COLOR_ONE,
  APP_NAME,
  HOME_PAGE_NAME,
  LOGIN_PAGE_NAME,
  REGISTER_PAGE_NAME,
  MY_ACCOUNT_PAGE_NAME,
  FAVORITE_SYMBOL_COLOR,
  FAVORITE_SYMBOL_BACKGROUND_COLOR,
  FAVORITE_MOVIE_SYMBOL,
  MESSAGE_DURATION,
  DASHBOARD_MOBILE_FONT_SIZE,
  DASHBOARD_LAPTOP_FONT_SIZE,
  INPUT_BACKGROUND_COLOR,
  MOBILE_MOVIES_GRID_GAP,
  LAPTOP_MOVIES_GRID_GAP,
  LAPTOP_MOVIE_CARD_FONT_SIZE,
  BUTTON_MAX_WIDTH,
  INPUT_MAX_WIDTH,
  MESSAGES_TIMEOUT,
  REDIRECT_TIMEOUT,
  MOBILE_MAX_WIDTH,
};
